name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - master  # Deploy only when master is updated

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.RASPBERRY_PI_IP }} >> ~/.ssh/known_hosts

      - name: Deploy MagicMirror to Raspberry Pi
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.RASPBERRY_PI_USER }}@${{ secrets.RASPBERRY_PI_IP }} << 'EOF'
            cd MagicMirror
            git pull origin master
            npm install
            pm2 restart mm || pm2 start npm --name "mm" -- start
